### ISSUE TITLE
Symbols in condition name prevent conditional logic from working correctly.

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#128]
Whew, this one was a doozy.

If you set the name of the condition to have mathematical symbols anywhere, the logic in OnTask fails to work for that condition.

For e.g., if I name the condition ">=80" or "MT mark >=80", the ontask message is not correct. Picture is worth a thousand words:

<img width="1426" alt="bug" src="https://user-images.githubusercontent.com/2507459/53141235-3a14ca00-3544-11e9-809c-20ee8b8f84eb.png">

I suspect this may be the case for other chars like ><!~%^= but I haven't tested them all thoroughly.

Potential fixes:
- prevent funny chars in condition names and/or
- fix the backend to escape any funny chars

workaround: don't use funny chars in condition names

**Comment by abelardopardo** [comment]
I partially understand the error but I cannot see the difference in the screen capture. I will check the code handling special characters in the condition names to see if I can replicate it.

**Comment by firasm** [comment]
Oops, sorry I should have annotated it. See attached. The "hello world" text doesn't appear in the top row with the special chars in the condition title, but does in the bottom row

<img width="1426" alt="annotated" src="https://user-images.githubusercontent.com/2507459/53205744-10ab7b00-35e4-11e9-8b6b-9c4155bf9a94.png">

**Comment by abelardopardo** [comment]
I've detected an anomaly but it appears when renaming a condition. Could this be the case in your example?

**Comment by abelardopardo** [comment]
Aha! Now I think I see the problem. I believe it has to do with the anomaly that I just found. Here is a quick test. Can you write two independent conditions, identical formula, one with the first name G>=80 and the other G greater than 80, and use them to control text? 

My guess is that it will behave as expected. The problem appears if you rename one condition from one name to the other. Can you confirm?

**Comment by firasm** [comment]
Just tested and I reproduced the bug my way: only the condition with the >= in the condition name doesn't work (without any renaming).

I've attached the workflow I used to test, along with the data. 
[ontask_workflow_190221_155006.gz](https://github.com/abelardopardo/ontask_b/files/2891770/ontask_workflow_190221_155006.gz)

**Comment by abelardopardo** [comment]
Fixed in release B.4.1

**Comment by dfoung** [comment]
Hi, I am afraid this problem still exists. 
As suggested, I wrote two independent conditions, identical formula, one with a symbol  "q2>3" [i.e. with a ">" / Screenshot at a top left] and the other without a symbol "q2larger3" [i.e. Screenshot top-right], and use them to control text [Screenshot at bottom]. However, only yhe one without a symbol woks. 
![screenshots](https://user-images.githubusercontent.com/55891161/65989183-07b63e00-e43e-11e9-8e55-5b6f39b76f8c.png)
