### ISSUE TITLE
problem with Privacy Badger extension in Chrome and OnTask

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#149]
Issue with OnTask functionality when Privacy Badger extension is installed in Chrome web browser but not Firefox

This is an interesting one that I have not experienced in prior versions of OnTask as I have been happily using Privacy Badger for years to manage trackers. With the latest version of OnTask (4.3.4) I have had to uninstall Privacy Badger from my Chrome library of extensions but interestingly it has not been an issue within Firefox plugin add-ons.
 
To reproduce the behaviour:
1. Use Chrome browser with [Privacy Badger extension](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) installed
2. login to OnTask v4.3.4 environment
3. Notice that the WYSIWYG tool is missing and the "insert column value" button does not work when Privacy Badger is active. *A few other functions also do not work as well.

with Privacy Badger active
![Screen Shot 2019-05-02 at 4 51 31 PM](https://user-images.githubusercontent.com/14169588/57057185-18318380-6cfb-11e9-8e3a-331ca47c5461.png)

With Privacy Badger extension uninstalled
![Screen Shot 2019-05-02 at 4 57 30 PM](https://user-images.githubusercontent.com/14169588/57057243-6fcfef00-6cfb-11e9-9e37-8350098d59ae.png)

This behaviour does not occur when using Firefox with Privacy Badger installed and active.

**Desktop:**
 - iOS
 - Browsers - Chrome Version 74.0.3729.131 (Official Build) (64-bit) and Firefox Version 66.0.3 (64-bit).

**Comment by abelardopardo** [comment]
We just pushed a patch to fix a bug precisely in that menu. Could you please if that new version (4.3.5) shows the same behaviour?

**Comment by leichtweis** [comment]
> We just pushed a patch to fix a bug precisely in that menu. Could you please if that new version (4.3.5) shows the same behaviour?

Just upgraded to v4.3.5 and the WYSIWYG toolbar and other buttons appear to be behaving properly again. Did notice that the version control in the footer of the tool still shows v4.3.4 even though the update information specifically references v4.3.5


![ontask version screenshot](https://user-images.githubusercontent.com/14169588/57264586-cd32ba00-70c6-11e9-8fad-cb42086d6ed2.png)

**Comment by abelardopardo** [comment]
Yes, good point. As part of the performance measures we included in the last release, OnTask now caches portions of the page to generate the answers quicker. The footer is one of them. The copy in the cache will eventually expire and the new version will show up. Nothing to worry about. There is an additional command that you can included in the upgrade process to flush the cache. I'll make sure it is included in the next release instructions.

Best.
